ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: nginx
  tls:
      - hosts:
          - gazprom-api.banzai-predict.site
        secretName: letsencrypt-dns
  hosts:
    - host: gazprom-api.banzai-predict.site
      paths:
        - path: /
          pathType: Prefix
config:
  SERVER_PORT: 80
  MODEL_BEHAVIOR_URI: http://gazprom-model-behavior.gazprom-model-behavior:8080
  MODEL_INTERCEPTOR_URI: http://gazprom-model-interceptor.gazprom-model-interceptor:8080
  KEYCLOAK_ISSUER_URI: https://gazprom-auth.banzai-predict.site/realms/gazprom-mrkt
  KEYCLOAK_CLIENT_ID: gateway-client
  KEYCLOAK_CLIENT_SECRET: NZh1y4kFE1WTPC7TUwgWdLIh1qrLSBs0