ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    kubernetes.io/ingress.class: nginx
  tls:
  #    - hosts:
  #        - gazprom.banzai-predict.site
  #      secretName: letsencrypt-dns
  hosts:
    - host: gazprom-api.banzai-predict.site
      paths:
        - path: /
          pathType: Prefix
config:
  SERVER_PORT: 80
  SPRING_CLOUD_GATEWAY_ROUTES_0_URI: "gazprom-model-interceptor.gazprom-model-interceptor:8080"
  SPRING_CLOUD_GATEWAY_ROUTES_0_ID: model
  SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES: Path=/api/model/*
  SPRING_CLOUD_GATEWAY_ROUTES_1_URI: "gazprom-user-feedback.gazprom-user-feedback:8080"
  SPRING_CLOUD_GATEWAY_ROUTES_1_ID: user-feedback
  SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES: Path=/api/feedback/*