---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gazprom-ml-service.fullname" . }}
  labels:
    {{- include "gazprom-ml-service.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
