version: '3.9'

services:
  app:
    image: swr.ru-moscow-1.hc.sbercloud.ru/gazprom-mrkt/banzai-frontend:latest
    environment:
      API_URL: http://api-gateway:8083
    build:
      context: ./frontend
    ports:
      - 4000:80
  api-gateway:
    container_name: api-gateway
    build: 
      context: ./backend/api-gateway
    ports:
      - 8083:8083
    environment:
      SERVER_PORT: 8083
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://model-interceptor:8080
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: model
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES: Path=/api/model/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://model-behavior:8080
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: model-behavior
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES: Path=/api/feedback/**
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/banzai-realm/${KEYCLOAK_BANZAI_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_BANZAI_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_BANZAI_CLIENT_SECRET}
    
  model-interceptor:
    container_name: model-interceptor
    build: 
      context: ./backend
      dockerfile: model-interceptor/Dockerfile
    environment:
      RMQ_HOST: rmq
      RMQ_PORT: 5672
      RMQ_USERNAME: ${RMQ_USERNAME}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      RMQ_ROUTING_KEY: ${RMQ_BEHAVIOR_QUEUE}
      MODEL_URL: http://model:8080/v1
    depends_on:
      - rmq

  model-behavior:
    container_name: model-behavior
    build: 
      context: ./backend
      dockerfile: model-behavior/Dockerfile
    environment:
      RMQ_HOST: rmq
      RMQ_PORT: 5672
      RMQ_USERNAME: ${RMQ_USERNAME}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      RMQ_BEHAVIOR_QUEUE: ${RMQ_BEHAVIOR_QUEUE}
      RMQ_FEEDBACK_POST_QUEUE: ${RMQ_FEEDBACK_POST_QUEUE}
      RMQ_FEEDBACK_RESPONSE_QUEUE: ${RMQ_FEEDBACK_RESPONSE_QUEUE}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${BEHAVIOR_DB_USER}
      DB_PASSWORD: ${BEHAVIOR_DB_PASSWORD}
      DB_NAME: ${BEHAVIOR_DB_NAME}
      MODEL_URL: http://model:8080/v1
    depends_on:
      - rmq

  model:
    container_name: model
    build:
      context: ./ml
      target: dev
    ports:
      # Swagger
      - 8080:8080
    volumes:
      - ./ml/models:/models
      - ./ml:/app
    
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - "9001:8080"
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

  db:
    container_name: model-behavior-db
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${BEHAVIOR_DB_USER}
      POSTGRES_PASSWORD: ${BEHAVIOR_DB_PASSWORD}
      POSTGRES_DB: ${BEHAVIOR_DB_NAME}
    restart: always

  rmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
