version: '3.9'

services:
  app:
    image: swr.ru-moscow-1.hc.sbercloud.ru/gazprom-mrkt/banzai-frontend:latest
    environment:
      API_URL: http://api-gateway:8088
      KEYCLOAK_CLIENT_ID: webapp
      KEYCLOAK_AUTHORITY: http://keycloak:8080/realms/webapp-realm
    ports:
      - 4000:80
  api-gateway:
    container_name: api-gateway
    build: 
      context: ./backend/api-gateway
    ports:
      - 8083:8088
    environment:
      SERVER_PORT: 8088
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/${KEYCLOAK_BANZAI_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_BANZAI_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_BANZAI_CLIENT_SECRET}
      MODEL_BEHAVIOR_URI: http://model-behavior:8081
      MODEL_INTERCEPTOR_URI: http://model-interceptor:8085
    depends_on:
      - keycloak
      - model-interceptor
      - model-behavior
    
  model-interceptor:
    container_name: model-interceptor
    build: 
      context: ./backend
      dockerfile: model-interceptor/Dockerfile
    environment:
      SERVER_PORT: 8085
      RMQ_HOST: rmq
      RMQ_PORT: 5672
      RMQ_USERNAME: ${RMQ_USERNAME}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      RMQ_ROUTING_KEY: ${RMQ_BEHAVIOR_QUEUE}
      MODEL_URL: http://model:8080/v1
    depends_on:
      - rmq

  model-behavior:
    container_name: model-behavior
    build: 
      context: ./backend
      dockerfile: model-behavior/Dockerfile
    ports:
      - 8090:8081
    environment:
      SERVER_PORT: 8081
      RMQ_HOST: rmq
      RMQ_PORT: 5672
      RMQ_USERNAME: ${RMQ_USERNAME}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      RMQ_BEHAVIOR_QUEUE: ${RMQ_BEHAVIOR_QUEUE}
      RMQ_FEEDBACK_POST_QUEUE: ${RMQ_FEEDBACK_POST_QUEUE}
      RMQ_FEEDBACK_RESPONSE_QUEUE: ${RMQ_FEEDBACK_RESPONSE_QUEUE}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${BEHAVIOR_DB_USER}
      DB_PASSWORD: ${BEHAVIOR_DB_PASSWORD}
      DB_NAME: ${BEHAVIOR_DB_NAME}
      MODEL_URL: http://model:8080/v1
    depends_on:
      - rmq

  model:
    container_name: model
    build:
      context: ./ml
      target: dev
    ports:
      # Swagger
      - 8080:8080
    volumes:
      - ./ml/models:/models
      - ./ml:/app
    
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - "9001:8080"
    command: ['start-dev']
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

  db:
    container_name: model-behavior-db
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${BEHAVIOR_DB_USER}
      POSTGRES_PASSWORD: ${BEHAVIOR_DB_PASSWORD}
      POSTGRES_DB: ${BEHAVIOR_DB_NAME}
    restart: always

  rmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
