server:
  port: ${SERVER_PORT:8080}
spring:
  rabbitmq:
    host: ${RMQ_HOST}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}
    template:
      routing-key: ${RMQ_ROUTING_KEY}
model:
  url: ${MODEL_URL}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
logging:
  level:
    root: DEBUG