server:
  port: ${SERVER_PORT:8080}
spring:
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}
  liquibase:
    enabled: true
    change-log: liquibase/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    date-format: banz.ai.marketing.bot.userfeedback.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
