openapi: 3.0.0
info:
  title: User feedback API
  version: 1.0.0
servers:
- url: /
paths:
  /feedback:
    post:
      operationId: postModelFeedback
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postModelFeedback_request'
        required: true
      responses:
        "201":
          description: feedback succesfully posted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
          description: error in feedback published
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
          description: internal server logic error
      summary: API to post model verdict feedback
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    apiError:
      properties:
        error:
          description: A brief description of the error
          type: string
        code:
          description: Error code indicating the specific error
          format: int32
          type: integer
      type: object
    postModelFeedback_request:
      properties:
        feedback:
          type: boolean
        userId:
          format: int64
          type: integer
      type: object
