server:
  port: ${SERVER_PORT:8080}
spring:
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}
  liquibase:
    enabled: true
    change-log: liquibase/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: validate
queues:
  feedback-post: ${RMQ_FEEDBACK_POST_QUEUE}
  feedback-response: ${RMQ_FEEDBACK_RESPONSE_QUEUE}
  behavior: ${RMQ_BEHAVIOR_QUEUE}
model:
  url: ${MODEL_URL}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
