argo-cd:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - gazprom.banzai-predict.site
  repoServer:
    containerSecurityContext:
      seccompProfile:
        type: Unconfined