apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gazprom-api-gateway=swr.ru-moscow-1.hc.sbercloud.ru/gazprom-mrkt/gazprom-api-gateway:latest
    argocd-image-updater.argoproj.io/gazprom-api-gateway.update-strategy: latest
  name: gazprom-api-gateway
spec:
  project: "default"
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: {{ .Values.gitRepo }}
    targetRevision: HEAD
    path: gazprom-api-gateway
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.env }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gazprom-api-gateway
