spring:
  cloud:
    gateway:
      routes:
        - id: model-behavior
          uri: ${MODEL_BEHAVIOR_URI}
          order: 1
          predicates:
            - Path=/api/model/query/model-request, /api/feedback
        - id: model-invoke
          uri: ${MODEL_INTERCEPTOR_URI}
          order: 2
          predicates:
            - Path=/api/model/evaluate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - health
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: DEBUG
keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}