spring:
  cloud:
    gateway:
      routes:
        - id: model
          uri: http://model-interceptor
          predicates:
            - Path=/api/model/*
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - health
server:
  port: ${SERVER_PORT}