ingress:
  enabled: true
#  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
#    - hosts:
#        - gazprom.banzai-predict.site
#      secretName: letsencrypt-dns
  hosts:
    - host: gazprom.banzai-predict.site
      paths:
        - path: /
          pathType: Prefix
