ingress:
  enabled: true
#  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    kubernetes.io/ingress.class: nginx
  tls:
    - hosts:
        - gazprom.banzai-predict.site
      secretName: letsencrypt-dns
  hosts:
    - host: gazprom.banzai-predict.site
      paths:
        - path: /
          pathType: Prefix

extraEnv:
  - name: API_URL
    value: https://gazprom-api.banzai-predict.site
  - name: KEYCLOAK_CLIENT_ID
    value: webapp
  - name: KEYCLOAK_AUTHORITY
    value: https://gazprom-auth.banzai-predict.site/realms/gazprom-mrkt