name: Infra CI workflow
on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yaml'
    branches:
      - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/sber/global
    steps:
      # Download previously shared build
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      # Copy the files from build folder to the S3 bucket
      - name: Init terraform
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.SBC_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.SBC_SECRET_KEY}}
          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
        run: terraform init
      - name: Plan terraform
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.SBC_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.SBC_SECRET_KEY}}
          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
        run: terraform plan
      - name: Deploy terraform
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.SBC_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.SBC_SECRET_KEY}}
          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
        run: terraform apply -auto-approve
  deploy-stage:
    needs:
      - deploy
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.SBC_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.SBC_SECRET_KEY}}
      SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
      SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/sber/staging
    steps:
      # Download previously shared build
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      # Copy the files from build folder to the S3 bucket
      - name: Init terraform
        run: terraform init
      - name: Plan terraform
        run: terraform plan
      - name: Deploy terraform
        run: terraform apply -auto-approve