name: Infra CI workflow
on:
  push:
    paths:
      - 'infra/**'
    branches:
      - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/sber/global
    steps:
      # Download previously shared build
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      # Copy the files from build folder to the S3 bucket
      - name: Init terraform
        env:
          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
        run: terraform init
      - name: Plan terraform
        env:
          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
        run: terraform plan
      - name: Deploy terraform
        env:
          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
        run: terraform apply -auto-approve
#  deploy-stage:
#    needs:
#      - deploy
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./sber/global
#    steps:
#      # Download previously shared build
#      - name: Checkout the repository to the runner
#        uses: actions/checkout@v3
#
#      - name: Setup Terraform with specified version on the runner
#        uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: 1.3.7
#      # Copy the files from build folder to the S3 bucket
#      - name: Init terraform
#        env:
#          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
#          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
#        run: terraform init
#      - name: Plan terraform
#        env:
#          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
#          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
#        run: terraform plan
#      - name: Deploy terraform
#        env:
#          SBC_ACCESS_KEY: ${{secrets.SBC_ACCESS_KEY}}
#          SBC_SECRET_KEY: ${{secrets.SBC_SECRET_KEY}}
#        run: terraform apply -auto-approve